version: '3.8'
services:
  devcontainer:
    build: 
      context: ../
      network: host
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: bridge
    ports:
      - "443:443"
    command: sleep infinity


